name: test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch or tag to publish (manual run)"
        required: true
  pull_request:
  push:

jobs:
  build_libs:
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86_64"]
        # python-version: ["cp39", "cp310", "cp311", "cp312", "cp313", "cp314"]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: cyx-6/tvm-ffi
          ref: torch-c-dlpack-script
          fetch-depth: 0
          submodules: recursive
          path: tvm-ffi
      - run: |
          dir C:\
          dir D:\
          Get-CimInstance -ClassName Win32_diskdrive | Select-Object DeviceID,FreeSpace,Size
          Get-WmiObject -Class Win32_LogicalDisk -ComputerName LOCALHOST | ? {$_. DriveType -eq 3} | select DeviceID, {[int]($_.Size /1GB)}, {[int]($_.FreeSpace /1GB)}
      # - name: prepare docker environment
      #   run: |
      #     docker pull quay.io/pypa/manylinux_2_28_${{ matrix.arch }}:latest
      #     docker run --name build_lib -d quay.io/pypa/manylinux_2_28_${{ matrix.arch }}:latest tail -f /dev/null
      #     docker cp tvm-ffi build_lib:/tvm-ffi
      # - name: build torch libs
      #   run: |
      #     docker exec -w /tvm-ffi build_lib bash ./addons/torch_c_dlpack_ext/build_aot_libs.sh
